Helm update
datakaveri/iudx-deployment pull request #102
Opened 2022-03-23 09:15 UTC by pranavv0

2022-03-23 11:28 UTC, abhi4578 commented on K8s-deployment/Charts/gis-interface/example-aws-resource-values.yaml
> +    limits:
Add node selector to be t3.medium for each verticle deployment pod

2022-03-23 12:09 UTC, karun-singh requested changes

2022-03-24 10:39 UTC, karun-singh commented on K8s-deployment/Charts/gis-interface/example-secrets/secrets/config.json
> +    "zookeeper"
```suggestion
    "zookeeper.zookeeper.svc.cluster.local"
```

2022-03-24 10:39 UTC, karun-singh commented on K8s-deployment/Charts/gis-interface/install.sh
> +helm install gis-interface -f resource-values.yaml -f values.yaml ../gis-interface/ -n gis
```suggestion
helm install gis-interface -f resource-values.yaml -f values.yaml ../gis-interface/ $@ -n gis
```
To pass arguments for setting helm values through the shell script if required.

2022-04-11 06:52 UTC, merged