Docker best practices for  elk server
datakaveri/iudx-deployment pull request #111
Opened 2022-03-31 04:59 UTC by THARAK-RAM1

* Splitting of elk stack file into 3 stack files
* Adding resource limits,reservations and PIDS through separate stack file
* Exposing elk server port through separate stack file
* Added logging driver for elk server
* Created example env file for kibana service

2022-04-06 05:38 UTC, hackcoderr approved these changes
ok to test

2022-04-06 09:52 UTC, abhi4578 requested changes

2022-04-06 09:52 UTC, abhi4578 commented on Docker-Swarm-deployment/single-node/elk/database-stack.yml
>        - xpack.security.enabled=true
upgrade to elastic, logstash, kibana to  7.12.1 . for elastic and logstash use this image ghcr.io/datakaveri/elasticsearch:7.12.1.  ghcr.io/datakaveri/logstash:7.12.1. 

the above elastic image contains s3 plugin, no need to iclude the volume. the launcher script and  https://github.com/datakaveri/iudx-deployment/blob/master/K8s-deployment/resource-server/database/elasticsearch/docker/Dockerfile

2022-04-06 09:52 UTC, abhi4578 commented on Docker-Swarm-deployment/single-node/elk/database-stack.yml
>        - xpack.security.enabled=true
@THARAK-RAM1

2022-06-08 04:47 UTC, abhi4578 approved these changes

2022-06-08 06:15 UTC, merged