Helm keycloak updates [install script]
datakaveri/iudx-deployment pull request #127
Opened 2022-06-14 14:17 UTC by karun-singh

- Fixed secret creation commands.
- Updated add repo command with appropriate commit URL for the required index containing the keycloak chart version used in IUDX.

2022-06-15 05:27 UTC, abhi4578 approved these changes
LGTM

2022-06-15 05:39 UTC, abhi4578 requested changes
seperate resource values (memory, cpu, storageclass, node-selector) for elastic, kibana and logstash for azure and aws.

2022-06-15 08:10 UTC, karun-singh commented
- Created example resource value yamls for aws and azure. 
- Renamed keycloak-values.yaml to values.yaml to make the naming consistent with other components.
- Updated README

2022-06-16 09:00 UTC, abhi4578 approved these changes

2022-06-16 09:16 UTC, merged