Docker: Mon-stack Version update
datakaveri/iudx-deployment pull request #174
Opened 2022-09-07 06:13 UTC by pranavv0

Mon-stack Update:
 1. Grafana: 7.2.2 to 9.191 (https://logmanager-docker.iudx.io/)
     Loki: 2.0.0 to 2.6.1
     Promtail: 2.0.0 to 2.6.1
     Prometheus: Updated to 2.38(Latest)
2. Update in Stack file
3. Updated grafan/Dockerfile
4. Updated grafana/Readme

2022-09-09 06:18 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/monitoring-stack/mon-stack.yaml
> +    image: prom/prometheus
Mention the image version/tag

2022-09-09 06:18 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/monitoring-stack/mon-stack.yaml
> +     - ./.grafana.env
Keep this env file in `secrets/` directory itself. Or update in the README secrets directory structure.

2022-09-09 07:46 UTC, abhi4578 requested changes
Please add software update changes on top of the refactor done in #156 . please see the commits
1. merge node exporter ansible to infra provision : https://github.com/datakaveri/iudx-deployment/pull/156/commits/5c2ef409fb9fcf3e4b29d5c2c4954b37468c34c0
    - move mon-stack/ansible to infrastructure dir
3. refactor mon-stack: https://github.com/datakaveri/iudx-deployment/pull/156/commits/aa4a2bd7b104fba0e3e8cff2b136a0987cecf5f8
    - simplify deployment
    - add resources, custom stack file
    - remove certs, as its no longer required, TLS through nginx
    - '.yml' files to '.yaml' files

- also update node-exporter, blackbox


@pranavv0

2022-09-09 08:00 UTC, abhi4578 commented
Better to close this PR and add the changes in new one

2022-09-11 12:42 UTC, closed without merging

2022-09-11 12:44 UTC, pranavv0 commented
Continued in another PR