Catalogue update
datakaveri/iudx-deployment pull request #187
Opened 2022-09-22 09:33 UTC by pranavv0

Update:
1. added Rating and Databroker Verticles.
2.  updated images tag
3.  changed respectively in Examples values

2022-09-26 06:27 UTC, abhi4578 commented
@pranavv0 please also include necessary changes for swarm based deployment for catalogue

2022-09-26 06:28 UTC, abhi4578 requested changes
@pranavv0 please also include necessary changes for swarm based deployment for catalogue

2022-09-26 10:02 UTC, abhi4578 commented
Update readme with new values @pranavv0

2022-09-26 10:17 UTC, abhi4578 commented
Integrate profanity check deployment to  cat hem repo

2022-09-26 17:06 UTC, abhi4578 commented on K8s-deployment/Charts/catalogue/templates/profanity-checker-sdk/deployment.yaml
> +          image: {{ template "catalogue.image" . }}
How is profanity check sdk image set?

2022-09-26 17:06 UTC, abhi4578 commented on K8s-deployment/Charts/catalogue/templates/profanity-checker-sdk/deployment.yaml
> +            - name: hazelcast
Not needed. hazelcast port

2022-09-26 17:19 UTC, pranavv0 commented on K8s-deployment/Charts/catalogue/templates/profanity-checker-sdk/deployment.yaml
> +          image: {{ template "catalogue.image" . }}
Yet to commit that

2022-09-26 17:19 UTC, pranavv0 commented on K8s-deployment/Charts/catalogue/templates/profanity-checker-sdk/deployment.yaml
> +            - name: hazelcast
okk

2022-09-27 02:15 UTC, abhi4578 requested changes
LGTM until now. Add 
1. please also include necessary changes for swarm based deployment for catalogue
2. Add values to Readme file

2022-10-03 04:56 UTC, abhi4578 approved these changes
LGTM

2022-10-03 04:57 UTC, merged