Rancher k8s upgrade
datakaveri/iudx-deployment pull request #205
Opened 2022-12-13 04:04 UTC by pranavv0

Updated Rancher Version to 2.6.9
Updated HPA to autoscale/v2

2022-12-13 04:32 UTC, abhi4578 commented
Upgrade the cloud init scripts with new rancher version @pranavv0

2022-12-13 17:49 UTC, abhi4578 commented
@pranavv0 also upgrade cloud init scripts in aws

2022-12-13 18:09 UTC, abhi4578 commented
Tasks remaining @pranavv0 
- [ ] Use azure file csi instead of azurefile in-tree as its depreciated
- [ ] Add ebs-csi-storage-class in example aws resource values and remove ebs-storage-class as its depreciated
- [ ] Upgrade Nginx ingress as it uses depreciated PSP , PDB
- [ ] Upgrade cloud init scripts in aws

2022-12-15 13:24 UTC, abhi4578 commented
@pranavv0 please merge the master branch to ur local branch and resolve conflicts. Also please cherry pick commits and pull another PR at 4.0.0 branch

2022-12-15 13:25 UTC, abhi4578 commented
We no longer using databroker manifest files, use helm files

2022-12-15 15:11 UTC, karun-singh approved these changes

2022-12-17 04:24 UTC, abhi4578 requested changes

2022-12-17 04:24 UTC, abhi4578 commented on K8s-deployment/K8s-cluster/addons/storage/azure/README.md
> +For in-tree azuredisk drivers, ```kubernetes.io/azure-file``` provisioner can be used in the [azurefile-storage-class.yaml](./azurefile-storage-class.yaml).
Document azurefile csi drivers
- Minimum k8s version - 1.21+
- Pre-requisites
- Installation of csi drivers through helm chart with commands 
and ref: https://github.com/kubernetes-sigs/azurefile-csi-driver#install-driver-on-a-kubernetes-cluster

2022-12-17 04:24 UTC, abhi4578 commented on K8s-deployment/K8s-cluster/addons/storage/azure/README.md
> +## Deployment with AzureDisk csi drivers
This section is repeated, its documented before in same readme

2022-12-19 15:25 UTC, merged