Cluster autoscaler to 1.24.0
datakaveri/iudx-deployment pull request #297
Opened 2023-01-11 13:57 UTC by pranavv0

2023-02-06 05:13 UTC, abhi4578 requested changes
Please review changes and test against test cluster @pranavv0

2023-02-06 10:00 UTC, pranavv0 commented on K8s-deployment/K8s-cluster/addons/cluster-autoscaler/azure/cluster-autoscaler-autodiscover.yaml
>              requests:
You might have interchanged the limits with requests key, limits values should be greater to requests

2023-02-08 08:25 UTC, abhi4578 commented
Can you test again? @pranavv0

2023-02-09 05:26 UTC, abhi4578 approved these changes

2023-02-09 05:27 UTC, merged