K8s:Added Encryption verticle deployment code  to RS Server
datakaveri/iudx-deployment pull request #366
Opened 2023-03-16 05:31 UTC by THARAK-RAM1

2023-03-16 08:11 UTC, pranavv0 reviewed
LGTM

2023-03-16 09:36 UTC, abhi4578 requested changes
Generate Helm Charts READMEs' tables  based on values YAML file metadata using this tool - https://github.com/bitnami-labs/readme-generator-for-helm

eg: https://github.com/datakaveri/iudx-deployment/tree/master/K8s-deployment/Charts/resource-server#apiserver-parameters

2023-03-17 05:11 UTC, abhi4578 requested changes
Also add async verticle parameters table

2023-03-17 05:11 UTC, abhi4578 commented on K8s-deployment/Charts/resource-server/example-azure-resource-values.yaml
> +    node.kubernetes.io/instance-type: t3a.medium
The nodeSelector should be node.kubernetes.io/instance-type: Standard_B2s
for azure

2023-03-17 05:11 UTC, abhi4578 commented on K8s-deployment/Charts/resource-server/README.md
> +| `encryption.autoscaling.enabled`                   | Enable Horizontal POD autoscaling for Apache                                                         | `true`
It should be ``Enable Horizontal POD autoscaling for encryption``  and even all the remaining things related to autoscaling params

2023-03-17 05:59 UTC, abhi4578 commented
Also add async verticle parameters table @THARAK-RAM1

2023-03-17 11:17 UTC, abhi4578 approved these changes

2023-03-17 11:19 UTC, merged