[Docker-swarm] Software Update: ELK v8.7.0
datakaveri/iudx-deployment pull request #448
Opened 2023-04-18 13:20 UTC by karun-singh

- Moved to bitnami elk images
- Updated elk stack to v8.7.0

2023-04-19 06:24 UTC, karun-singh commented
- [ ] update ES cert generation script

2023-04-21 07:23 UTC, abhi4578 requested changes

2023-05-01 11:27 UTC, abhi4578 requested changes

2023-05-01 11:27 UTC, abhi4578 commented on Docker-Swarm-deployment/single-node/elk/database-stack.yaml
> +      - LOGSTASH_HEAP_SIZE=500m
Shift the ``LOGSTASH_HEAP_SIZE=500m`` to resources stack file

2023-05-01 11:52 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/elk/database-stack.yaml
> +      - ELASTICSEARCH_KEYSTORE_LOCATION=/opt/bitnami/elasticsearch/config/certs/elastic-certificates.p12
This is the tls keystore and truststore, not the same as elasticsearch.keystore. It expects either a Java keystore (jks) or a PKCS#12 file.

2023-05-01 11:56 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/elk/elasticsearch/elasticsearch.yaml
> +xpack.security.transport.ssl.keystore.path: /opt/bitnami/elasticsearch/config/certs/elastic-certificates.p12
Might be redundant and not needed after setting the location from the env variable. Will test and update.

2023-05-01 11:59 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/elk/database-stack.yaml
> +      - ELASTICSEARCH_ENABLE_SECURITY=true
Updated

2023-05-02 07:39 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/elk/elasticsearch/elasticsearch.yaml
> +xpack.security.transport.ssl.keystore.path: /opt/bitnami/elasticsearch/config/certs/elastic-certificates.p12
Tested, it is redundant as the path is being set by the env variable itself. Removed.

2023-05-02 09:45 UTC, abhi4578 approved these changes

2023-05-02 10:23 UTC, merged