Added Helm chart for DMP APD
datakaveri/iudx-deployment pull request #699
Opened 2024-04-17 13:18 UTC by iSRIDHARRAO

2024-04-18 08:22 UTC, pranavv0 commented on K8s-deployment/Charts/dmp-apd/example-aws-resource-values.yaml
> +apiServer:
remane this to a dmpApd, and remove other for other verticles

2024-08-02 10:15 UTC, karun-singh requested changes

2024-08-02 10:15 UTC, karun-singh commented on K8s-deployment/Charts/dmp-apd/README.md
> +## Create secret files
Please add the example secrets dir with a config template and env file.

2024-08-02 10:17 UTC, karun-singh commented on K8s-deployment/Charts/dmp-apd/README.md
> +## Create secret files
Please remove the kubescape badge as well.

2024-08-06 09:25 UTC, karun-singh requested changes
update the env and config files with these changes.

2024-08-06 09:25 UTC, karun-singh commented on K8s-deployment/Charts/dmp-apd/example-secrets/secrets/.dmpapd.env
> +
```suggestion
DMP_APD_URL=https://<dmp-apd-url>
LOG_LEVEL=INFO
```

2024-08-06 09:25 UTC, karun-singh commented on K8s-deployment/Charts/dmp-apd/example-secrets/secrets/config.json
> +  "version": "1.0",
```suggestion
  "version": "1.0",
  "zookeepers": [
    "zookeeper.zookeeper.svc.cluster.local"
  ],
```

2024-08-07 07:27 UTC, karun-singh approved these changes
LGTM

2024-08-07 07:27 UTC, merged