moved grafana configuration files
datakaveri/iudx-deployment pull request #709
Opened 2024-05-14 05:37 UTC by sivanaikk

- Moved configuration from docker directory

2024-07-01 06:34 UTC, abhi4578 commented
@karun-singh can you review this?

2024-07-01 06:47 UTC, karun-singh commented
@sivanaikk Please also add the grafana env with smtp config options in the `example-secrets` dir

2024-07-25 11:22 UTC, karun-singh requested changes

2024-07-25 11:22 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/catalogue/example-secrets/secrets/cat-summary-config.json
> +    "host": "localhost",
Since it is running in swarm, host will always be tasks.postgres right?
```suggestion
    "host": "tasks.postgres",
```

2024-07-25 11:22 UTC, karun-singh commented on Docker-Swarm-deployment/single-node/catalogue/example-secrets/secrets/cat-summary-config.json
> +    "database": "<postgres rs database>",
```suggestion
    "database": "iudx_rs",
```

2024-08-01 05:29 UTC, karun-singh approved these changes
LGTM

2024-08-01 05:29 UTC, merged