K8s:auditing cache verticle
datakaveri/iudx-deployment pull request #711
Opened 2024-05-21 07:35 UTC by pranavv0

1. Added cache verticles in helm
2. It contains deployment and hpa
3. Updated in Readme as well

2024-05-21 11:39 UTC, karun-singh requested changes

2024-05-22 07:39 UTC, pranavv0 commented on K8s-deployment/Charts/auditing-server/example-secrets/secrets/config.json
> +      "postgersApdTableName": "auditing_acl_apd",
can you give me those keys to add or where I can refer those? coz its not available on https://github.com/datakaveri/auditing-server/tree/5.5.0/example-configs

2024-05-22 07:41 UTC, karun-singh commented on K8s-deployment/Charts/auditing-server/example-secrets/secrets/config.json
> +      "postgersApdTableName": "auditing_acl_apd",
Please take from the staging deployment config.

2024-05-24 07:54 UTC, karun-singh approved these changes

2024-05-24 07:55 UTC, merged