Modified the Catalouge helm chart to run as a single verticle
datakaveri/iudx-deployment pull request #727
Opened 2024-08-29 06:36 UTC by sivanaikk

- Modified values.yaml to remove all the verticles except apiServer
- Modified aws and azure resource-values files to have only resources and limits of single verticle

2024-09-02 08:19 UTC, karun-singh commented
Update app and chart versions in Chart.yaml

2024-09-25 07:48 UTC, karun-singh requested changes

2024-09-25 07:48 UTC, karun-singh commented on K8s-deployment/Charts/catalogue/example-aws-resource-values.yaml
Increase the resources since all verticles will run in single pod now.

2024-09-25 07:48 UTC, karun-singh commented on K8s-deployment/Charts/catalogue/example-azure-resource-values.yaml
Increase the resources since all verticles will run in single pod now.

2024-09-25 07:48 UTC, karun-singh commented on K8s-deployment/Charts/catalogue/templates/deployment.yaml
Change deployment name, container name and labels to catalogue-server, to avoid confusion. Also update selectors in service and target ref in HPA.

2025-03-10 06:09 UTC, sivanaikk commented on K8s-deployment/Charts/catalogue/templates/deployment.yaml
updated the PR with the changes

2025-03-11 08:25 UTC, karun-singh approved these changes

2025-03-11 08:26 UTC, merged