Keycloak yml added.
datakaveri/iudx-deployment pull request #73
Opened 2021-11-22 11:10 UTC by hackcoderr

2021-11-22 11:15 UTC, abhi4578 commented
- Please add only key cloak related files in commits to the PR.

2021-11-22 11:18 UTC, abhi4578 reviewed
- In docker swarm,  a standalone keycloak is deployed and clustered. Can removed clustered setup.

2021-11-23 10:37 UTC, hackcoderr commented
> * Please add only key cloak related files in commits to the PR.  i.e. those that will belong to single/keycloak folder https://github.com/hackcoderr/iudx-deployment/tree/keycloak/Docker-Swarm-deployment/single-node/keycloak. You can remove all other things - auth, file-server installation docs @hackcoderr

@abhi4578  I m working on keycloak problem only and have gone through your all comments.

2021-11-23 12:42 UTC, abhi4578 commented on Docker-Swarm-deployment/single-node/keycloak/keycloak.yml
> +version: "2"
https://github.com/datakaveri/iudx-deployment/tree/master/Docker-Swarm-deployment/single-node/auth-cred-db

2021-12-06 11:24 UTC, abhi4578 requested changes

2021-12-06 11:24 UTC, abhi4578 commented on Docker-Swarm-deployment/single-node/keycloak/keycloak-stack.yml
> +    depends_on:
depends on does not work in stack file/ swarm deployment. 

How is the keycloak connecting to postgres ? And also reuse postgres  stack filee defined in  single-node/postgres folder

2021-12-16 07:39 UTC, abhi4578 commented
This is the next step :

2021-12-16 07:40 UTC, abhi4578 commented
This is the next step
- Bring a nginx proxy in-front of keycloak and test if its working. Set up reverse proxy, ssl, rate limits , refer [ keycloak official docs](https://www.keycloak.org/docs/latest/server_installation/#_setting-up-a-load-balancer-or-proxy), [blog](https://itnext.io/nginx-as-reverse-proxy-in-front-of-keycloak-21e4b3f8ec53)
   -  Verifying the configuration https://www.keycloak.org/docs/latest/server_installation/#verifying-the-configuration

Its also mentioned here.https://github.com/datakaveri/iudx-deployment/issues/59

2021-12-17 12:13 UTC, abhi4578 commented
This is the next step

    Bring a nginx proxy in-front of keycloak and test if its working. Set up reverse proxy, ssl, rate limits , refer keycloak official docs, blog
        Verifying the configuration https://www.keycloak.org/docs/latest/server_installation/#verifying-the-configuration

Its also mentioned here.#59 @hackcoderr

2021-12-20 06:48 UTC, abhi4578 commented
- keycloak bitnami image , version 14.0.0
- nginx 1.20

2021-12-24 13:21 UTC, abhi4578 commented
closes issue #59

2022-02-08 06:44 UTC, abhi4578 approved these changes

2022-02-08 06:47 UTC, merged