[Superset] Superset Docker Swarm files
datakaveri/iudx-deployment pull request #741
Opened 2024-09-27 12:37 UTC by SRINI2410

### Why this PR?
Creating Stack files and configuration files for deploying superset visualization tool for analytics

2024-09-30 07:01 UTC, karun-singh requested changes

2024-09-30 07:01 UTC, karun-singh commented on Docker-Swarm-deployment/analytics/superset_env_file
Please hard code env variables that will not change for our deployments. 
Ex- DB/redis hosts and ports.

2024-09-30 07:17 UTC, SRINI2410 commented on Docker-Swarm-deployment/analytics/superset_env_file
> +MAPBOX_API_KEY=''
@karun-singh, Mapbox key must be generated from https://www.mapbox.com/ and using that key we make use of mapbox service for map related visualization

2024-09-30 07:17 UTC, SRINI2410 commented on Docker-Swarm-deployment/analytics/superset_env_file
Updated

2024-09-30 07:17 UTC, SRINI2410 commented on Docker-Swarm-deployment/analytics/README.md
updated

2024-09-30 07:37 UTC, karun-singh commented on Docker-Swarm-deployment/analytics/superset_env_file
> +MAPBOX_API_KEY=''
@swarup-e can you please provide a document/guide on how this key has to be generated. We can add it to the readme along with deployment files.

2025-04-08 07:05 UTC, karun-singh approved these changes

2025-04-21 09:03 UTC, karun-singh approved these changes

2025-04-21 09:03 UTC, merged

2025-04-21 09:05 UTC, karun-singh commented
@SRINI2410 Merged to close this PR, but the Dockerfiles need improvements. and `/docker/superset/docker` dir is not needed and can be removed. 
Please create another PR to the 5.6.0 branch for these changes.